# Generated by Django 4.2.14 on 2024-07-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-timestamp'], 'verbose_name': 'История поиска', 'verbose_name_plural': 'История поиска'},
        ),
    ]
